---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-entrytask-com-v1-podservice
  failurePolicy: Fail
  name: mpodservice.kb.io
  rules:
  - apiGroups:
    - app.entrytask.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-entrytask-com-v1-podservice
  failurePolicy: Fail
  name: vpodservice.kb.io
  rules:
  - apiGroups:
    - app.entrytask.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podservices
  sideEffects: None
