apiVersion: v1
kind: Service
metadata:
  name: example-prometheus
spec:
  type: NodePort
  ports:
    - name: https
      nodePort: 30901
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
